# Generated by Django 5.0.6 on 2026-06-15 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_providers', '0001_initial'),
        ('keyword_research', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_keyword', models.CharField(blank=True, max_length=255)),
                ('wp_category_id', models.IntegerField(blank=True, help_text='WordPress Category ID', null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_meta_description', models.TextField(blank=True)),
                ('seo_focus_keyword', models.CharField(blank=True, max_length=255)),
                ('images_count', models.IntegerField(default=2, help_text='Number of inline images requested')),
                ('content_html', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/featured/')),
                ('inline_images', models.JSONField(blank=True, default=list, help_text='List of saved image paths')),
                ('internal_links_used', models.JSONField(blank=True, default=list, help_text='Links injected by AI')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating Content'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('publishing', 'Publishing to WordPress'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('wp_post_id', models.IntegerField(blank=True, help_text='ID of the draft post in WordPress', null=True)),
                ('custom_instructions', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_config_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_providers.aiproviderconfig')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_jobs', to='sites.site')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keyword_research.contenttopic')),
            ],
        ),
    ]
