# Generated by Django 5.0.6 on 2026-06-15 11:31

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سایت')),
                ('domain', models.URLField(unique=True, verbose_name='آدرس دامنه')),
                ('wp_url', models.URLField(verbose_name='آدرس API وردپرس')),
                ('wp_username', models.CharField(max_length=150, verbose_name='نام کاربری وردپرس')),
                ('wp_app_password', models.CharField(max_length=255, verbose_name='رمز عبور اپلیکیشن وردپرس')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
            ],
            options={
                'verbose_name': 'سایت',
                'verbose_name_plural': '۱. سایت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='KeywordResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='کلمه کلیدی')),
                ('intent', models.CharField(choices=[('Informational', 'اطلاعاتی (Informational)'), ('Commercial', 'تجاری (Commercial)'), ('Transactional', 'معاملاتی (Transactional)'), ('Navigational', 'ناوبری (Navigational)')], max_length=50, verbose_name='هدف جستجو (Intent)')),
                ('category_pillar', models.CharField(max_length=255, verbose_name='دسته\u200cبندی مادر (Pillar Page)')),
                ('article_title', models.CharField(max_length=500, verbose_name='عنوان مقاله پیشنهادی خوشه\u200cای')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('deleted', 'حذف شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ تولید')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='seo_services.site', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'دیتای کیورد ریسرچ',
                'verbose_name_plural': '۴. بانک کلمات کلیدی و عناوین',
            },
        ),
        migrations.CreateModel(
            name='GeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مقاله')),
                ('slug', models.CharField(max_length=255, verbose_name='اسلاگ (URL)')),
                ('content', models.TextField(verbose_name='متن کامل مقاله (Markdown/HTML)')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو (Yoast/RankMath)')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='متا دسکریپشن')),
                ('image_count', models.IntegerField(default=1, verbose_name='تعداد تصاویر مابین متن')),
                ('featured_image_url', models.URLField(blank=True, null=True, verbose_name='لینک تصویر شاخص')),
                ('wp_post_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه پست در وردپرس')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس در پلتفرم'), ('sent_to_wp', 'ارسال شده به وردپرس (Draft)'), ('published', 'منتشر شده روی سایت')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ تولید')),
                ('published_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار زمان\u200cبندی شده')),
                ('keyword_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo_services.keywordresearch', verbose_name='کلمه کلیدی مرجع')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='seo_services.site', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'مقاله تولید شده',
                'verbose_name_plural': '۵. کارخانه تولید مقاله',
            },
        ),
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('keyword', 'تحقیق کلمات کلیدی'), ('article', 'تولید مقاله سئو شده')], max_length=20, verbose_name='نوع فرآیند')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (Direct)'), ('gapgpt', 'GapGPT API'), ('gemini', 'Google Gemini')], default='gapgpt', max_length=20, verbose_name='پرووایدر هوش مصنوعی')),
                ('model_name', models.CharField(default='gpt-5-mini', max_length=100, verbose_name='نام دقیق مدل')),
                ('temperature', models.FloatField(default=0.7, verbose_name='میزان خلاقیت (Temperature)')),
                ('max_tokens', models.IntegerField(default=4000, verbose_name='حداکثر توکن مصرفی')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to='seo_services.site', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات هوش مصنوعی',
                'verbose_name_plural': '۳. تنظیمات هوش مصنوعی سایت\u200cها',
                'unique_together': {('site', 'feature_type')},
            },
        ),
        migrations.CreateModel(
            name='SiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر سایت'), ('editor', 'نویسنده / ویرایشگر')], default='editor', max_length=20, verbose_name='سطح دسترسی')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='seo_services.site', verbose_name='سایت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_permissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر',
                'verbose_name_plural': '۲. سطوح دسترسی کاربران',
                'unique_together': {('user', 'site')},
            },
        ),
    ]
