# Generated by Django 5.0.6 on 2026-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='کلید API اختصاصی'),
        ),
    ]
