# Generated by Django 5.0.6 on 2026-06-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0002_aiconfig_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedarticle',
            name='current_step',
            field=models.CharField(choices=[('idle', 'در انتظار شروع پردازش'), ('links', '🔗 ۱. در حال استخراج و تحلیل لینک\u200cهای داخلی وردپرس'), ('text', '✍️ ۲. در حال نگارش متن جامع و تگ\u200cهای متای سئو'), ('images', '🖼️ ۳. در حال طراحی تصاویر اختصاصی مدیا با هوش مصنوعی'), ('assembly', '📦 ۴. در حال ساختاردهی نهایی و تزریق کدهای HTML'), ('success', '✅ ۵. عملیات تولید با موفقیت کامل پایان یافت'), ('failed', '❌ خطا در فرآیند تولید محتوا')], default='idle', max_length=30, verbose_name='مرحله فعلی تولید'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='error_log',
            field=models.TextField(blank=True, null=True, verbose_name='گزارش دقیق خطا برای اصلاح کاربر'),
        ),
        migrations.AddField(
            model_name='site',
            name='automation_interval_days',
            field=models.IntegerField(default=2, verbose_name='فاصله زمانی تولید خودکار (روز)'),
        ),
        migrations.AddField(
            model_name='site',
            name='content_type',
            field=models.CharField(choices=[('educational', 'آموزشی و راهنما (Educational)'), ('commercial', 'بررسی محصول و تجاری (Commercial)'), ('news', 'خبری و ترند روز (News)'), ('corporate', 'شرکتی و معرفی خدمات (Corporate)')], default='educational', max_length=100, verbose_name='نوع و ساختار پیش\u200cفرض محتوا'),
        ),
        migrations.AddField(
            model_name='site',
            name='is_automation_active',
            field=models.BooleanField(default=False, verbose_name='اتوماسیون زمان\u200cبندی فعال است؟'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='feature_type',
            field=models.CharField(choices=[('keyword', 'تحقیق کلمات کلیدی'), ('article_text', 'تولید متن مقاله'), ('article_image', 'تولید تصویر مقاله')], max_length=20, verbose_name='نوع فرآیند'),
        ),
        migrations.AlterField(
            model_name='generatedarticle',
            name='content',
            field=models.TextField(blank=True, verbose_name='متن کامل مقاله'),
        ),
        migrations.AlterField(
            model_name='generatedarticle',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='generatedarticle',
            name='slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسلاگ (URL)'),
        ),
    ]
