# Generated by Django 5.0.6 on 2026-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0003_generatedarticle_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='keyword_current_step',
            field=models.CharField(choices=[('idle', 'در انتظار شروع تحقیق کلمات'), ('serper', '🔍 ۱. اسکرپ زنده نتایج گوگل و ردیابی کانتنت\u200cگپ رقبا'), ('llm', '🧠 ۲. پردازش مهندسی هوش مصنوعی و استخراج خوشه\u200cهای محتوایی'), ('saving', '📦 ۳. سازمان\u200cدهی و ذخیره\u200cسازی ساختار یافته عناوین در دیتابیس'), ('success', '✅ ۴. فرآیند تحقیق کلمات با موفقیت پایان یافت'), ('failed', '❌ خطا در فرآیند تحقیق کلمات کلیدی')], default='idle', max_length=30, verbose_name='مرحله فعلی تحقیق کلمات'),
        ),
        migrations.AddField(
            model_name='site',
            name='keyword_error_log',
            field=models.TextField(blank=True, null=True, verbose_name='لاگ خطای تحقیق کلمات'),
        ),
        migrations.AlterField(
            model_name='keywordresearch',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('generated', 'مقاله تولید شده 📝'), ('deleted', 'حذف شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
