# Generated by Django 5.0.6 on 2026-06-15 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_description', models.TextField()),
                ('seed_keywords', models.TextField()),
                ('competitor_urls', models.JSONField(blank=True, default=list)),
                ('depth_option', models.CharField(choices=[('basic', 'کم (۱۵-۲۰ موضوع)'), ('standard', 'متوسط (۴۰-۵۰ موضوع)'), ('deep', 'عمیق (۸۰-۱۰۰ موضوع)')], default='standard', max_length=20)),
                ('domain_focus', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_ai_output', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_jobs', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sites.site')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='keyword_research.keywordresearchjob')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='sites.site')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='keyword_research.keywordresearchjob')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_keyword', models.CharField(blank=True, max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('used_for_article', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='sites.site')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='keyword_research.keywordcategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='keyword_research.keywordresearchjob')),
            ],
        ),
    ]
