# Generated by Django 5.0.6 on 2026-06-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI Direct'), ('gapgpt', 'GapGPT (Multi-model proxy)'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('custom', 'Custom Endpoint')], max_length=50)),
                ('name', models.CharField(help_text='e.g., GapGPT - GPT4o or Gemini Pro', max_length=100)),
                ('api_key', models.CharField(max_length=512)),
                ('base_url', models.URLField(blank=True, help_text='Required for custom or proxy endpoints like GapGPT')),
                ('model_name', models.CharField(help_text='e.g., gpt-4o, gemini-1.5-pro', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_for_site', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, help_text='If null, this is a global config managed by Super Admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('tone_of_voice', models.CharField(blank=True, default='رسمی', max_length=255)),
                ('target_word_count', models.IntegerField(default=1200)),
                ('internal_links_min', models.IntegerField(default=2)),
                ('internal_links_max', models.IntegerField(default=5)),
                ('seo_plugin', models.CharField(choices=[('rankmath', 'RankMath'), ('yoast', 'Yoast SEO')], default='rankmath', max_length=50)),
                ('images_count_default', models.IntegerField(default=2)),
                ('custom_instructions', models.TextField(blank=True)),
                ('ai_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_providers.aiproviderconfig')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_profile', to='sites.site')),
            ],
        ),
    ]
